version: '3.8'
services:
  db:
    image: postgres:15
    container_name: prod-pg
    volumes:
      - prod_db:/var/lib/postgresql/data/
    env_file:
          - ./.env
    restart: always
    networks:
      - localnet
    ports:
      - "5432:5432"

  test-db:
    image: postgres:15
    container_name: test-pg
    volumes:
      - test_db:/var/lib/postgresql/data/
    env_file:
      - ./.env
    restart: always
    networks:
      - localnet
    ports:
      - "5431:5432"

  app:
    build: .
    container_name: webtronics-app
    volumes:
      - ./:/code
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - db
      - test-db
    networks:
      - internet
      - localnet

  web:
    image: nginx:1.25.2-alpine-slim
    container_name: nginx
    volumes:
     - ./templates:/etc/nginx/templates
     - ./nginx.conf:/etc/nginx/conf.d/default.conf
     - media_value:/data/media/
    ports:
     - "80:80"
    restart: always
    depends_on:
      - app
    networks:
      - internet

volumes:
  prod_db:
  test_db:
  media_value:

networks:
  localnet:
    name: localnet
    driver: bridge
  internet:
    name: internet
    driver: bridge
