version: '3.8'
services:
  db:
    image: postgres:15
    container_name: prod-db
    volumes:
      - prod_db:/var/lib/postgresql/data/
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    restart: always
    networks:
      - localnet
    ports:
      - "5432:5432"

  app:
    image: myapp:v01
    container_name: prod-app
    volumes:
      - ./:/code
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - db
    networks:
      - internet
      - localnet

  web:
    image: nginx:1.25.2-alpine-slim
    container_name: nginx
    volumes:
     - ./templates:/etc/nginx/templates
     - ./nginx.conf:/etc/nginx/conf.d/default.conf
     - media_value:/data/media/
    ports:
     - "80:80"
    restart: always
    depends_on:
      - app
    networks:
      - internet

volumes:
  prod_db:
  media_value:

networks:
  localnet:
    name: localnet
    driver: bridge
  internet:
    name: internet
    driver: bridge
